//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeInfo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Name can not be blank")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Age can not be empty")]
        [Range(1, Int32.MaxValue, ErrorMessage ="Age can not be less than 1")]
        public int Age { get; set; }
        public string Marital_Status { get; set; }
        [Required(ErrorMessage = "Salary can not be empty")]
        [Range(0, Int32.MaxValue, ErrorMessage = "Salary can not be negative")]
        public int Salary { get; set; }
        public string Location { get; set; }
    }
}
